### ISSUE TITLE
Files are not uploaded if the filename contains accented characters

### ISSUE THREAD

**Issue by maxthev** [linuxserver/docker-papermerge#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior

I am living in France, so many filenames use é, è, à etc as accented characters.
normally, it should work : [see related issue](https://github.com/ciur/papermerge/issues/188)

## Current Behavior

Files are not uploaded if the filename contains accented characters.

## Steps to Reproduce

1. Log in papermerge admin (i'm using firefox)
2. Drag and drop a PDF with a title like "contrat signé.pdf"
3. The pdf is not uploaded and is not present in the file system (empty folder)

## Environment
**OS:** Ubuntu 18.04.2 LTS (virtual machine - ESXI)
**CPU architecture:** Ryzen 2200G - ESXI
**How docker service was installed:** 

```YAML
  papermerge:
    image: linuxserver/papermerge
    container_name: ${CLIENT}.papermerge
    ports:
      - 8084:8000
    volumes:
      - ../volume/papermerge/config:/config
      - ../volume/papermerge/data:/data
      - /mnt/edms:/edms
    environment:
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/mods:papermerge-multilangocr
      - OCRLANG=fra
    restart: unless-stopped
```

## Docker logs
this error block appear multiple time :

```LOG
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 25: ordinal not in range(128)
Call stack:
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/mgclipboard/middleware/clipboard.py", line 214, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/papermerge/papermerge/core/views/decorators.py", line 36, in inner
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/app/papermerge/papermerge/core/views/documents.py", line 366, in upload
    logger.debug("upload for f=%s user=%s", f, request.user)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.

```

**Comment by aostanin** [comment]
I ran into this same problem with Japanese characters. It looks like the locale is set to `en_US.UTF-8` but this locale isn't actually available in the container:

```bash
$ docker exec papermerge locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory

$ docker exec papermerge locale -a
C
C.UTF-8
POSIX
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
```

I was able to work around this by setting the locale to `C.UTF-8` for now:

```yaml
environment:
  - LANG=C.UTF-8
  - LANGUAGE=C.UTF-8
```

It looks like the other linuxserver containers I'm using have `en_US.UTF-8` available, but not Papermerge.

**Comment by aptalca** [comment]
Hmm, this one is based on the focal baseimage, unlike most others, which are based on bionic. That could account for the difference

**Comment by l4rm4nd** [comment]
Can confirm the issue also for German umlauts like ä, ü, ö, Ä, Ü, Ö in the filename of uploaded documents. 
File can be uploaded, but the PDF rendering breaks. Example filename `testü.pdf`

![grafik](https://user-images.githubusercontent.com/21357789/100548869-a707d880-326f-11eb-8c6e-aa8d2dcf7788.png)
