### ISSUE TITLE
MySql/MariaDB Error: MySQL does not allow unique CharFields to have a max_length > 255

### ISSUE THREAD

**Issue by alexkoon** [linuxserver/docker-papermerge#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Clean log.

## Current Behavior
logs are spinning with the following error repeated periodically:

```
,
ERRORS:
core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.
[uwsgi-daemons] throttling "/usr/bin/python3 ./manage.py worker" for 1 seconds
[uwsgi-daemons] respawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 911)
SystemCheckError: System check identified some issues:

```

## Steps to Reproduce
1. Config settings with the following
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'papermerge',
        'USER': 'papermerge',
        'PASSWORD': 'papermerge',
        'HOST': 'mariadb.mydomain.com',
        'PORT': 3306,
    },
}
```
2. Start the container

## Environment
**OS:** Debian Buster
**CPU architecture:** x86_64
**How docker service was installed:** Latest version from hub.docker.com

## Command used to create docker container (run/create/compose/screenshot)
```
    environment:
      - PUID=1000
      - PGUID=100
      - TZ=Europe/London
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=config.settings.production
    hostname: bac75115f1bc
    image: linuxserver/papermerge:version-v1.5.5

    ports:
      - 8081:8000/tcp
    restart: always
    volumes:
      - /opt/config:/config
      - /opt/dockerdata/papermerge:/data


```
## Docker logs
```
[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... 

usermod: no changes


-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/



Brought to you by linuxserver.io

-------------------------------------


To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------


User uid:    1000

User gid:    911

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 50-config: executing... 

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.


0 static files copied to '/app/papermerge/static', 129 unmodified.

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.


System check identified 1 issue (0 silenced).

mv: cannot stat '/defaults/uwsgi.ini': No such file or directory

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 86, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 74, in execute

    return self.cursor.execute(query, args)

  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute

    res = self._query(query)

  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query

    db.query(q)

  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 226, in query

    _mysql.connection.query(self, query)

MySQLdb._exceptions.IntegrityError: (1364, "Field 'mail_by_secret' doesn't have a default value")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/app/papermerge/manage.py", line 24, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 328, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 369, in execute

    output = self.handle(*args, **options)

  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/shell.py", line 92, in handle

    exec(sys.stdin.read())

  File "<string>", line 7, in <module>

  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/models.py", line 147, in create_user

    return self._create_user(username, email, password, **extra_fields)

  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/models.py", line 141, in _create_user

    user.save(using=self._db)

  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/base_user.py", line 66, in save

    super().save(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 748, in save

    self.save_base(using=using, force_insert=force_insert,

  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 785, in save_base

    updated = self._save_table(

  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 890, in _save_table

    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)

  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 927, in _do_insert

    return manager._insert(

  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 82, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1204, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1394, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 68, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 86, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 86, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 74, in execute

    return self.cursor.execute(query, args)

  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute

    res = self._query(query)

  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query

    db.query(q)

  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 226, in query

    _mysql.connection.query(self, query)

django.db.utils.IntegrityError: (1364, "Field 'mail_by_secret' doesn't have a default value")

[cont-init.d] 50-config: exited 1.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[uWSGI] getting INI configuration from uwsgi.ini

353:C 13 Feb 2021 17:24:36.379 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

353:C 13 Feb 2021 17:24:36.379 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=353, just started

353:C 13 Feb 2021 17:24:36.379 # Configuration loaded

[uwsgi-static] added mapping for /static => /app/papermerge/static

*** Starting uWSGI 2.0.18-debian (64bit) on [Sat Feb 13 17:24:36 2021] ***

compiled with version: 10.0.1 20200405 (experimental) [master revision 0be9efad938:fcb98e4978a:705510a708d3642c9c962beb663c476167e4e8a4] on 11 April 2020 11:15:55

os: Linux-5.9.0-0.bpo.5-amd64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31)

nodename: bac75115f1bc

machine: x86_64

clock source: unix

pcre jit disabled

detected number of CPU cores: 12

current working directory: /app/papermerge

detected binary path: /usr/bin/uwsgi-core

your memory page size is 4096 bytes

detected max file descriptor number: 1048576

353:M 13 Feb 2021 17:24:36.380 * Running mode=standalone, port=6379.

353:M 13 Feb 2021 17:24:36.380 # Server initialized

353:M 13 Feb 2021 17:24:36.380 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

building mime-types dictionary from file /etc/mime.types...567 entry found

lock engine: pthread robust mutexes

353:M 13 Feb 2021 17:24:36.380 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

thunder lock: disabled (you can enable it with --thunder-lock)

353:M 13 Feb 2021 17:24:36.380 * Ready to accept connections

uwsgi socket 0 bound to TCP address :8000 fd 3

Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]

Python main interpreter initialized at 0x5644a747ae70

python threads support enabled

your server socket listen backlog is limited to 100 connections

your mercy for graceful operations on workers is 60 seconds

mapped 145840 bytes (142 KB) for 1 cores

*** Operational MODE: single process ***

WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5644a747ae70 pid: 355 (default app)

*** uWSGI is running in multiple interpreter mode ***

spawned uWSGI master process (pid: 355)

spawned uWSGI worker 1 (pid: 375, cores: 1)

[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 911)

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

[uwsgi-daemons] throttling "/usr/bin/python3 ./manage.py worker" for 1 seconds

[uwsgi-daemons] respawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 911)

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

[uwsgi-daemons] throttling "/usr/bin/python3 ./manage.py worker" for 1 seconds

[uwsgi-daemons] respawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 911)

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

[uwsgi-daemons] throttling "/usr/bin/python3 ./manage.py worker" for 1 seconds

[uwsgi-daemons] respawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 911)

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

[uwsgi-daemons] throttling "/usr/bin/python3 ./manage.py worker" for 1 seconds

[uwsgi-daemons] respawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 911)

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

[uwsgi-daemons] throttling "/usr/bin/python3 ./manage.py worker" for 2 seconds

[uwsgi-daemons] respawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 911)

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

[uwsgi-daemons] respawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 911)

SystemCheckError: System check identified some issues:


ERRORS:

core.Document.digest: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

```

**Comment by tobbenb** [comment]
You have used the wrong env variable for PGID.
And why have you set all those env variables? Please remove them and test again.

**Comment by alexkoon** [comment]
I corrected the PGID, removed all envs apart form PUID, PGID and TZ. Same result with the logs.

The values were derived from testing when I tried a bare metal install of papermerge on a test system. The latest papermerge from github standalone has the settings in papermerge.conf.py to allow you to set the values:

```
DBTYPE = "mariadb"
DBUSER = "papermerge"
DBPASS = "papermerge"
DBHOST = "mariadb.mydomain.com"
DBNAME = "papermerge"
```

Then in the base/settings/base.py they have (check the elif in the extract below - this is the part that reads in the env vars above to configure the mysql/mariadb connection):
```
if cfg_papermerge.get("DBTYPE", False) in (
    "pg", "postgre", "postgres", "postgresql"
):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": cfg_papermerge.get("DBNAME", "papermerge"),
        "USER": cfg_papermerge.get("DBUSER", "papermerge"),
    }
    DATABASES["default"]["PASSWORD"] = cfg_papermerge.get("DBPASS", "")
    DATABASES["default"]["HOST"] = cfg_papermerge.get("DBHOST", "localhost")
    DATABASES["default"]["PORT"] = cfg_papermerge.get("DBPORT", 5432)
elif cfg_papermerge.get("DBTYPE", False) in (
    "my", "mysql", "maria", "mariadb"
):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.mysql",
        "NAME": cfg_papermerge.get("DBNAME", "papermerge"),
        "USER": cfg_papermerge.get("DBUSER", "papermerge"),
    }
    DATABASES["default"]["PASSWORD"] = cfg_papermerge.get("DBPASS", "")
    DATABASES["default"]["HOST"] = cfg_papermerge.get("DBHOST", "localhost")
    DATABASES["default"]["PORT"] = cfg_papermerge.get("DBPORT", 3306)
    # Requires MySQL > 5.7.7 or innodb_large_prefix set to on
    SILENCED_SYSTEM_CHECKS = ['mysql.E001']
```

I have just noticed the **SILENCED_SYSTEM_CHECKS = ['mysql.E001']** in the bare metal install of papermerge in their base.py. Just tried it now with the docker image as well and this fixed the issue.

So the fix will be to add **SILENCED_SYSTEM_CHECKS = ['mysql.E001']** to docker-papermerge/root/defaults/papermerge.conf.py per the original papermerge project?

**Comment by tobbenb** [comment]
I'm a little bit confused about why you are referencing the base.py file and where you actually modify your settings. So please do this.

- Start from scratch. That means delete your /config and /data volume bind mounts.
- Start up the container and check the logs that it starts without errors.
- Change the settings for the database in papermerge.conf.py and restart your container.
- Check the logs.

I have just set it up here without errors using mariadb. So looks like you messed up your config somewhere.

**Comment by alexkoon** [comment]
Did as requested, I deleted all /config and /data volumes. Started the container in a pristine state. This starts up fine with no errors. Checked the data volume and the sqllite files etc were there.

Dropped the database and user and recreated new user with blank papermerge database in mariadb. Stopped the container. Edited papermerge.conf.py to uncomment out the DBTYPE and filled in the DBxxx values correctly.
Started the container again and the logs are clear and looks good. However, when I checked the papermerge database, the database was still empty. When checking the mariadb, I don't see any connections for papermerge either (via myphpadmin).

If I remember correctly, when the papermerge process starts, the logs shows some migration process and information about the database tables being created. I don't see this in the latest logs. 

So clean logs but no connection to mariadb still.

**Comment by tobbenb** [comment]
Looks like you have to edit the settings.py file for papermerge to pick up the database. I have never used it before, so not sure why there are multiple places. Looks like the database settings in papermerge.conf.py doesn't really do anything.

**Comment by alexkoon** [comment]
Yes it looks like intention for the settings.py to run and pick up the settings from the conf is not working as intended or skipped with the docker image version (unlike the bare metal papermerge).

The fix seems to be to cut and paste the settings.py from papermerge itself (and keep the previous linuxserver.io database block to maintain current compatibility :

```
# Existing settings from linuxserver.io settings.py
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "/data/papermerge.db",
    }
}

# Proposed addition from ciur/papermerge base.py to select database override if defined from conf
if cfg_papermerge.get("DBTYPE", False) in (
    "pg", "postgre", "postgres", "postgresql"
):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": cfg_papermerge.get("DBNAME", "papermerge"),
        "USER": cfg_papermerge.get("DBUSER", "papermerge"),
    }
    DATABASES["default"]["PASSWORD"] = cfg_papermerge.get("DBPASS", "")
    DATABASES["default"]["HOST"] = cfg_papermerge.get("DBHOST", "localhost")
    DATABASES["default"]["PORT"] = cfg_papermerge.get("DBPORT", 5432)
elif cfg_papermerge.get("DBTYPE", False) in (
    "my", "mysql", "maria", "mariadb"
):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.mysql",
        "NAME": cfg_papermerge.get("DBNAME", "papermerge"),
        "USER": cfg_papermerge.get("DBUSER", "papermerge"),
    }
    DATABASES["default"]["PASSWORD"] = cfg_papermerge.get("DBPASS", "")
    DATABASES["default"]["HOST"] = cfg_papermerge.get("DBHOST", "localhost")
    DATABASES["default"]["PORT"] = cfg_papermerge.get("DBPORT", 3306)
    # Requires MySQL > 5.7.7 or innodb_large_prefix set to on
    SILENCED_SYSTEM_CHECKS = ['mysql.E001']
```

I have run the above with the DBTYPE commented out (so a sqllite database is created) and with it defined as mariadb and can see the database is populated with the tables from an empty database.

**Comment by tobbenb** [comment]
You don't have to mix anything. Just uncomment the database settings for MySQL in settings.py and adjust it to your need.
Closing it as it's no a bug in the container.
