### ISSUE TITLE
mglib missing in latest image and how to fix that

### ISSUE THREAD

**Issue by ciur** [linuxserver/docker-papermerge#32]
Hi guys,

Papermerge here.
I've done some internal refactoring which results in your latest docker build containing application which starts with following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 224, in fetch_command
    app_name = commands[subcommand]
KeyError: 'worker'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 231, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)


  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/papermerge/config/settings/production.py", line 1, in <module>
    from .base import *  # noqa
  File "/app/papermerge/config/settings/base.py", line 4, in <module>
    from mglib.utils import try_load_config
```
Problem reported by @l4rm4nd in ciur/papermerge#345.
The fix for this, is to install django first, and then requirements listed in requirements/* folder:
```
$ pip install django==3.1.7              
$ pip install -r requirements/base.txt
$ pip install -r requirements/...
```
Installing without first line will fail.
The root cause of the problem is [this line](https://github.com/papermerge/papermerge-core/blob/master/setup.cfg#L3) which will try to load django to figure out version of papermerge-core....
Anyway, just adding "pip3 install django==3.1.7" in [line here](https://github.com/linuxserver/docker-papermerge/blob/master/Dockerfile#L71) will fix the build.

**Comment by alex-phillips** [comment]
@ciur Awesome, thanks for the heads up! I'll open a PR now.

**Comment by alex-phillips** [comment]
Closed with a3a8f921648ed258cfee27c8cfa34cfa1b3113f2

**Comment by l4rm4nd** [comment]
Hi all,

many thanks for the quick PR. The papermerge web application is now up again and does not throw a server error anymore. However, there are still some error logs, which prevent the worker from properly running and importing documents (e.g. via IMAP consumption).

I'm running docker-papermerge ARM image v2.0.0rc48-ls30 on my Raspberry Pi 4.

The logs:

````
[uwsgi-daemons] respawning "/usr/bin/python3 ./manage.py worker" (uid: 1000 gid: 100)
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/papermerge/core/checks.py", line 110, in binaries_check
    binary = os.path.basename(binary_path)
  File "/usr/lib/python3.8/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[uwsgi-daemons] throttling "/usr/bin/python3 ./manage.py worker" for 111 seconds
````

@ciur: Any ideas?

**Comment by ciur** [comment]
@l4rm4nd, this issue is same as ciur/papermerge#344. 
There was a bug (was [fixed](https://github.com/ciur/papermerge/commit/3da0f26274d5e0a0f6e6c7be0171c550d929b9f5)) related to default value of BINARY_STAPLER setting.

Quick Intro: [stapler](https://pypi.org/project/stapler/) is a dependency for cut/pasting PDF pages. It is installed via pip utility. Papermerge uses it as command line - thus needs to know stapler's path. The problem is that it is hard know where that stapler thingy will be installed (e.g. it might be installed in python virtual environment, or maybe system wide ):)

There are at least two options:
- just wait couple of days until next release
- add BINARY_STAPLER setting in papermerge.conf.py (absolute path)

**Comment by l4rm4nd** [comment]
> @l4rm4nd, this issue is same as [ciur/papermerge#344](https://github.com/ciur/papermerge/issues/344).
> There was a bug (was [fixed](https://github.com/ciur/papermerge/commit/3da0f26274d5e0a0f6e6c7be0171c550d929b9f5)) related to default value of BINARY_STAPLER setting.
> 
> Quick Intro: [stapler](https://pypi.org/project/stapler/) is a dependency for cut/pasting PDF pages. It is installed via pip utility. Papermerge uses it as command line - thus needs to know stapler's path. The problem is that it is hard know where that stapler thingy will be installed (e.g. it might be installed in python virtual environment, or maybe system wide ):)
> 
> There are at least two options:
> 
> * just wait couple of days until next release
> * add BINARY_STAPLER setting in papermerge.conf.py (absolute path)

@ciur, yeah that was the issue! Many thanks 🥇 

For my RPi4, the location of stapler was

````
/usr/local/bin/stapler
````

Adding the following line at `papermerge.conf.py` fixed the issue:

````
BINARY_STAPLER = "/usr/local/bin/stapler"
````
